stages:
  data_preprocessing:
    cmd: python -m src.entrypoints.preprocess
    deps:
      - src/data/data_ingestion.py
      - src/data/data_preprocessing.py
      - data/raw/
      - params.yaml
    params:
      - data.raw_data_dir
    outs:
      - data/processed/
    
  train:
    cmd: python -m src.entrypoints.train
    deps:
      - src/model/train_utils.py
      - src/model/model_architecture.py
      - src/data/dataloader_for_torch.py
      - data/processed/
      - params.yaml
    params:
      - training.learning_rate
      - training.weight_decay
      - training.num_epochs
    outs:
      - artifacts